[package]
name = "hallo_welt"
version = "0.1.0"
authors = ["FlatheadV8"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffprobe = "0.1.0"
